import LeanLattices.Basic
import LeanLattices.IntegralLattice
import LeanLattices.DualAndDiscriminant
import LeanLattices.StandardLattices
import LeanLattices.DiscriminantForms
import LeanLattices.CoxeterAndReflectiveLattices
import LeanLattices.EnriquesSurfaceTheory
import LeanLattices.NikulinGluing
import LeanLattices.OverlatticesAndGluing
import LeanLattices.RationalFansAndSemifans
import LeanLattices.Algebra.BilinearForm.Basic
import LeanLattices.Algebra.BilinearForm.Dual
import LeanLattices.Algebra.BilinearForm.Discriminant
import LeanLattices.Algebra.Lattices.Standard
import LeanLattices.Categories.AlgebraicStack.Functors.SemitoroidalFunctor
import LeanLattices.Categories.AlgebraicStack.Morphisms.DeformationGroupoid
import LeanLattices.Categories.AlgebraicStack.Morphisms.StackMorphism
import LeanLattices.Categories.AlgebraicStack.Objects.AlgebraicSpace
import LeanLattices.Categories.AlgebraicStack.Objects.IntegralAffineManifold
import LeanLattices.Categories.AlgebraicStack.Objects.KSBAStack
import LeanLattices.Categories.AlgebraicStack.Objects.KulikovModel
import LeanLattices.Categories.ComplexManifold.Functors.PeriodMapFunctor
import LeanLattices.Categories.ComplexManifold.Morphisms.HolomorphicMap
import LeanLattices.Categories.ComplexManifold.Objects.ArithmeticQuotient
import LeanLattices.Categories.ComplexManifold.Objects.Domain
import LeanLattices.Categories.ComplexManifold.Objects.IntegralAffine
import LeanLattices.Categories.DiscriminantForm.Functors.GluingFunctor
import LeanLattices.Categories.DiscriminantForm.Morphisms.AntiIsometry
import LeanLattices.Categories.DiscriminantForm.Objects.Basic
import LeanLattices.Categories.DivisorGroup.Functors.PositivityFunctor
import LeanLattices.Categories.DivisorGroup.Objects.DivisorClass
import LeanLattices.Categories.FiniteFreeZModule.Functors.ScalarExtension
import LeanLattices.Categories.FiniteFreeZModule.Morphisms.LinearMap
import LeanLattices.Categories.FiniteFreeZModule.Objects.Basic
import LeanLattices.Categories.IntegralLat.Functors.DiscFunctor
import LeanLattices.Categories.IntegralLat.Morphisms.Embedding
import LeanLattices.Categories.IntegralLat.Morphisms.Involution
import LeanLattices.Categories.IntegralLat.Morphisms.Overlattice
import LeanLattices.Categories.IntegralLat.Morphisms.OverlatticeBijection
import LeanLattices.Categories.IntegralLat.Morphisms.PrimitiveEmbeddingExistence
import LeanLattices.Categories.IntegralLat.Morphisms.Reflection
import LeanLattices.Categories.IntegralLat.Objects.Basic
import LeanLattices.Categories.IntegralLat.Objects.Cusps
import LeanLattices.Categories.IntegralLat.Objects.Dual
import LeanLattices.Categories.IntegralLat.Objects.EvenLat
import LeanLattices.Categories.IntegralLat.Objects.Genus
import LeanLattices.Categories.IntegralLat.Objects.GramAndSum
import LeanLattices.Categories.IntegralLat.Objects.IsotropicQuotient
import LeanLattices.Categories.IntegralLat.Objects.Standard
import LeanLattices.Categories.IntegralLat.Objects.StandardRootLattices
import LeanLattices.Categories.IntegralLat.Objects.TwoElemLat
import LeanLattices.Categories.KSBAPair.Functors.SurfaceMMPFunctor
import LeanLattices.Categories.KSBAPair.Morphisms.DltContraction
import LeanLattices.Categories.KSBAPair.Objects.KSBAModuliProperness
import LeanLattices.Categories.KSBAPair.Objects.LogPair
import LeanLattices.Categories.KSBAPair.Objects.ReflexiveSheaf
import LeanLattices.Categories.KSBAPair.Objects.Singularities
import LeanLattices.Categories.QuadraticModule.Functors.DiscriminantFunctor
import LeanLattices.Categories.QuadraticModule.Morphisms.Isometry
import LeanLattices.Categories.RationalFan.Functors.ToricFunctor
import LeanLattices.Categories.RationalFan.Functors.Wythoff
import LeanLattices.Categories.RationalFan.Morphisms.FanMorphism
import LeanLattices.Categories.RationalFan.Objects.Cone
import LeanLattices.Categories.RationalFan.Objects.Fan
import LeanLattices.Categories.RationalFan.Objects.Semifan
import LeanLattices.Categories.ReflectionGroup.Functors.FoldingFunctor
import LeanLattices.Categories.ReflectionGroup.Morphisms.ChamberHom
import LeanLattices.Categories.ReflectionGroup.Objects.AffineDiagram
import LeanLattices.Categories.ReflectionGroup.Objects.Chambers
import LeanLattices.Categories.ReflectionGroup.Objects.CoxeterDatum
import LeanLattices.Categories.ReflectionGroup.Objects.OrientedHyperbolic
import LeanLattices.Categories.ReflectionGroup.Objects.Representation
import LeanLattices.Categories.ReflectionGroup.Objects.VinbergTheorem
import LeanLattices.Categories.Scheme.Divisors.Reflexive
import LeanLattices.Categories.Scheme.Functors.CyclicCover
import LeanLattices.Categories.Scheme.Functors.StructureSheafFunctor
import LeanLattices.Categories.Scheme.Morphisms.AnticanonicalQuotient
import LeanLattices.Categories.Scheme.Morphisms.BlowupMorphism
import LeanLattices.Categories.Scheme.Morphisms.CoverMorphism
import LeanLattices.Categories.Scheme.Morphisms.FamilyMorphism
import LeanLattices.Categories.Scheme.Morphisms.QuotientMorphism
import LeanLattices.Categories.Scheme.Morphisms.RDPResolution
import LeanLattices.Categories.Scheme.Morphisms.RelativeProj
import LeanLattices.Categories.Scheme.Morphisms.RelativeSpec
import LeanLattices.Categories.Scheme.Objects.Curve
import LeanLattices.Categories.Scheme.Objects.DltBoundary
import LeanLattices.Categories.Scheme.Objects.Surface
import LeanLattices.Categories.SymmBilinModuleCat.Functors.Forget
import LeanLattices.Categories.SymmBilinModuleCat.Morphisms.Hom
import LeanLattices.Categories.SymmBilinModuleCat.Objects.Basic

/-!
# Master Export Module

This root module imports the full modular architecture across all 12 milestones of the formalization program.
-/

namespace LeanLattices

def program_completion_target : String :=
  "Full 12-Milestone Formalization Program: Lattices, Coxeter Geometry, Fans, Relative Schemes, Surfaces, & KSBA Moduli"

end LeanLattices
