import LeanLattices.Categories.RationalFan.Objects.Semifan

namespace LeanLattices.Categories.RationalFan

open IntegralLat

/-- The semifan obtained by coarsening along the two-element group generated by an involution. -/
axiom WythoffCoarseningFunctor (L : IntegralLattice) (J : Involution L) (C : Cone L) :
  Semifan L

/-- The defining cones of the Wythoff coarsening are precisely the original cone and its
involutive translate. -/
axiom wythoff_coarsening_cones (L : IntegralLattice) (J : Involution L) (C : Cone L) :
  (WythoffCoarseningFunctor L J C).cones = wythoffCones L J C

/-- Restricting the Wythoff coarsening to the fixed lattice commutes with folding. -/
axiom generalized_fan_restriction_commutes_with_folding
    (L : IntegralLattice) (J : Involution L) (C : Cone L) :
  ∀ x ∈ FixedSublattice L J,
    x ∈ Submodule.span ℤ (Set.range C.generators.get) ↔
      ∃ σ ∈ (WythoffCoarseningFunctor L J C).cones,
        x ∈ Submodule.span ℤ (Set.range σ.generators.get)

end LeanLattices.Categories.RationalFan
