import LeanLattices.IntegralLattice
import LeanLattices.StandardLattices
import Mathlib.Analysis.InnerProductSpace.Basic
import Mathlib.LinearAlgebra.BilinearForm.Properties

/-!
# Hyperbolic Reflective Lattices, Coxeter Diagrams, and Chamber Foldings

This module formalizes:
- Hyperbolic spaces of signature $(1, n)$
- Reflection subgroups generated by root vectors $r \in L$ ($Q(r) = -2$ or $-1$)
- Hyperplane reflection $s_r(x) = x - \frac{2 B(x, r)}{B(r, r)} r$
- Coxeter matrices, simple root systems, and fundamental chambers
- Chamber folding under lattice involutions
-/

namespace IntegralLattice

variable {L : Type*} [AddCommGroup L] [Module ℤ L] [Module.Finite ℤ L] [Module.Free ℤ L]

/-- Reflection linear map on $L$. -/
def reflection (M : IntegralLattice L) (r : L)
    (_hr : M.quad r = -2 ∨ M.quad r = 2) : L →ₗ[ℤ] L :=
  let f : L →+ L := {
    toFun x := if M.quad r = -2 then x + (M.eval x r) • r else x - (M.eval x r) • r
    map_zero' := by simp [IntegralLattice.eval]
    map_add' := by
      intro x y
      by_cases h : M.quad r = -2
      · rw [if_pos h, if_pos h, if_pos h]
        dsimp [IntegralLattice.eval]
        rw [M.B.map_add, LinearMap.add_apply, add_zsmul]
        abel
      · rw [if_neg h, if_neg h, if_neg h]
        dsimp [IntegralLattice.eval]
        rw [M.B.map_add, LinearMap.add_apply, add_zsmul]
        abel
  }
  {
    toFun := f
    map_add' := f.map_add
    map_smul' := by
      intro c x
      exact map_intCast_smul f ℤ ℤ c x
  }











































/-- An involution $J \in O(L)$ is a lattice isometry with $J^2 = \text{id}$. -/
structure LatticeInvolution (M : IntegralLattice L) where
  toFun : L →ₗ[ℤ] L
  isIsometry : ∀ x y, M.eval (toFun x) (toFun y) = M.eval x y
  involution : ∀ x, toFun (toFun x) = x

/-- Folded root sum $\alpha_J = \alpha + J(\alpha)$ for a lattice involution. -/
def foldedRoot (M : IntegralLattice L) (J : LatticeInvolution M) (r : L) : L :=
  r + J.toFun r


end IntegralLattice
