module

public import LeanLattices.Categories.RationalFan.Objects.Fan
public import LeanLattices.Categories.IntegralLat.Morphisms.Involution

@[expose] public section

namespace LeanLattices.Categories.RationalFan

open IntegralLat

/-- A locally finite, group-equivariant collection of rational cones. -/
structure Semifan (L : IntegralLattice) where
  cones : Set (Cone L)
  locallyFinite : ∀ x : L.carrier,
    Set.Finite {σ | σ ∈ cones ∧ x ∈ Submodule.span ℤ (Set.range σ.generators.get)}
  group : Type
  [groupAction : Group group]
  action : group →* (L.carrier ≃ₗ[ℤ] L.carrier)
  equivariant : ∀ g σ, σ ∈ cones →
    ∃ τ ∈ cones, τ.generators = σ.generators.map (action g)

attribute [instance] Semifan.groupAction

/-- The Wythoff coarsening generated by the orbit of a cone under a lattice involution. -/
def wythoffCones (L : IntegralLattice) (J : Involution L) (σ : Cone L) : Set (Cone L) :=
  {τ | τ = σ ∨ τ.generators = σ.generators.map J.hom.toLinearMap}

end LeanLattices.Categories.RationalFan
